// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5G0m5cwClPToeVTSYxabwz4EadQqM710',
    appId: '1:81728778696:android:72a8f64d7a1dfd8a3010fd',
    messagingSenderId: '81728778696',
    projectId: 'chathive-9d484',
    storageBucket: 'chathive-9d484.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs77-JUlOuK7u6rlaCEsj9GhuCIewmjMM',
    appId: '1:81728778696:ios:1541a6396d4fc7ed3010fd',
    messagingSenderId: '81728778696',
    projectId: 'chathive-9d484',
    storageBucket: 'chathive-9d484.appspot.com',
    androidClientId: '81728778696-bqo6eqbe9p06li48gabg9a2kgc2bmc77.apps.googleusercontent.com',
    iosClientId: '81728778696-gk05i51no5ksl48muu8ee8mkr0qjcuj7.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatHive',
  );

}